### ISSUE TITLE
CODING - [khochaynhalam] - Coding common components

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#10]
> CC 
> 
> Dear @phamlinh221199 , @Vi1309 ,
> 
> Please help me provide the design for the common components and comment each item on this issue.
> 
> Thanks,
> TrungNhan
> 

Dear @LieuTran287 , @chinhminh2025  ,

Please help me implement for the `common` components based on the design that @phamlinh221199 and @Vi1309 provided:

### /estimate: 6h

Thanks,
TrungNhan.

> CC
> 
> Dear @Huong111 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the common component, please help me review them's source code and please check the quality
> 
> Thanks,
> TrungNhan.

> CC
> 
> Dear @phamlinh221199 , @Vi1309 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the common component, please help me check it fits the design or not. Then inform them if it is incorrect.
> 
> Thanks,
> TrungNhan.

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @phamlinh221199 , @Vi1309 , @Huong111 

I had completed this work.
Spend time: 4h
Please check my work in [link](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/ph1).
If it is incorrect, please inform me the wrong place.
 
Thanks,
Lieu
