### ISSUE TITLE
CODING - [khochaynhalam] - HOME - Hottest dishes

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#15]
Dear @chinhminh2025 ,

Please help me implement module hottest dishes in the home page based on the design:
![image](https://user-images.githubusercontent.com/52454131/87869357-503ce900-c9c9-11ea-97e1-436e630e3efe.png)

Thanks,
TrungNhan

**Comment by chinhminh2025** [comment]
Dear @nhanntdl,
I will take this work.
Estimate: 3h

Thanks,
Chinh

**Comment by chinhminh2025** [comment]
Dear @nhanntdl,
I have done this work.
Spent time 3h.
Please check it in [link](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/ph1)
Thanks,
Chinh
