### ISSUE TITLE
CODING - [khochaynhalam] - HOME - About us

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#16]
Dear  @Vi1309 ,

Please help me implement a module about us in the home page based on the design:
![image](https://user-images.githubusercontent.com/52454131/87869409-c8a3aa00-c9c9-11ea-9267-e7292178f783.png)

Thanks,
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I had completed this work.
Spend time: 1h
Please check my work in link.
If it is incorrect, please inform me the wrong place.

Thanks
Vi
