### ISSUE TITLE
CODING - [khochaynhalam] - HOME - Post

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#18]
Dear @LieuTran287  ,

Please help me implement module post on the home page based on the design:
![image](https://user-images.githubusercontent.com/52454131/87869466-51224a80-c9ca-11ea-9338-baefe1609ceb.png)

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Spend time: 3h
Please check my work in [link](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/ph1).
If it is incorrect, please inform me the wrong place.

Thanks,
Lieu
