### ISSUE TITLE
CODING - [khochaynhalam] - HOME - Banner

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#19]
Dear  @khochaynhalam-dev/khochaynhalam-team ,

Please help me implement the banner on the home page based on the design:
![image](https://user-images.githubusercontent.com/52454131/87869569-01904e80-c9cb-11ea-8f9c-04888193ee29.png)

Thanks,
TrungNhan

**Comment by chinhminh2025** [comment]
Dear @nhanntdl,
I will take this work.
Estimate: 2h
@LieuTran287 @Vi1309  and me will work together.
Thanks,
Chinh

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I, @Vi1309  and @chinhminh2025  had completed this work.
Spend time: 2h
Please check our work in [link](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/ph1).

Thanks,
Lieu
