### ISSUE TITLE
CODE - [khochaynhalam] - Build the base code

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#24]
#10 

Dear @Huong111  ,

Please help me build the base code for this project

Thanks,
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I will take this work.

Thanks,
Huong

**Comment by Huong111** [comment]
Dear @nhanntdl,

The time to complete this job is 2 hour.
Done:  create and edit file index.html, index.js, index.css.
Problem: I do not understand the file app.js ? 

Thanks,
Huong

**Comment by nhanntdl** [comment]
Dear @Huong111 ,

Please list out for me a list of your problems

Thanks
TrungNhan

**Comment by Huong111** [comment]
Dear @nhanntdl,

I don't understand app.js file. 
What is app.js file?  How does it work? Please.

Thanks,
Huong

**Comment by nhanntdl** [comment]
> Dear @nhanntdl,
> 
> I don't understand app.js file.
> What is app.js file? How does it work? Please.
> 
> Thanks,
> Huong

Dear @Huong111 ,

> What is app.js file?

**app.js** file is the javascript file of **only** index page, 

> How does it work?

`window.location.href = "../home/";`
It redirects your index page to home page as the default page,

`let bug = "";`
It just a declare of bug in your page, you don't need to care about it

So **index.js** file is the javascript file in **global scope**
So if you want to **script** your **single page**, you have to create a new javascript file that can **only be used** for your single page.

Thanks and best regards,
TrungNhan

**Comment by Huong111** [comment]
log time yesterday:
Spent time: 1h
Done: nghiên cứu file index.js và chỉnh sửa hoàn chỉnh source
Todo: giao task
Problem: N/A

**Comment by Huong111** [comment]
log time today:
Spent time: 30ph
Done: tạo nhánh #24, thảo luận nhóm.
Todo: commit, push
Problem: N/A

**Comment by Huong111** [comment]
log time 17/04/2020:
Spent time: 0h
Done: N/A
Todo: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 18/04/2020:
Spent time: 1h
Done:  khi viết quy tắc, thì đã xem lại source để có những đề xuất thống nhất với quy tắc.
Todo: tiếp túc kiểm tra source
Problem: N/A

**Comment by Huong111** [comment]
log time 19/04/2020:
Spent time: 0h
Done: N/A
Todo: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 20/04/2020:
Spent time: 0h
Done: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 21/04/2020:
Spent time: 0h
Done: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 22/04/2020:
Spent time: 0h
Done: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 23/04/2020:
Spent time: 0h
Done: N/A
Todo: hoàn thành task quy tắc, xem lại source hoàn chỉnh theo quy tắc chuẩn bị giao task.
Problem: N/A

**Comment by Huong111** [comment]
log time 24/04/2020:
Spent time: 0h
Done: N/A
Problem: N/A

**Comment by Huong111** [comment]
log time 25/04/2020:
Spent time: 0h
Done: N/A
Problem: N/A
