### ISSUE TITLE
Fanpage - [khochaynhalam] - Create fan page 

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#26]
Dear @Vi1309 

Please help me create a fanpage for this khochaynhalam.com 

Thanks,
TrungNhan

**Comment by Vi1309** [comment]
Spent time: 2h
Done: đã hoàn thành task này.
To do: N/A.
Problem: N/A.

Thanks
Vi

**Comment by nhanntdl** [comment]
> Dear @nhanntdl
> 
> Spent time: 2h
> Em đã hoàn thành cái task này.
> 
> Thanks
> Vi

Dear @Vi1309 

Good job
I will close this task
