### ISSUE TITLE
Fanpage - [khochaynhalam] - Create a store on fanpage 

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#27]
Dear @Vi1309 

Please help me create a store con the fanpage of khochaynhalam.com

Thanks,
TrungNhan

**Comment by Vi1309** [comment]
Spent time: 30p.
Done: đã hoàn thành task này.
To do: N/A.
Problem: N/A.

Thanks
Vi

**Comment by nhanntdl** [comment]
Dear @Vi1309 

Ok good.
I will close thí task

Thanks
TrungNhan
