### ISSUE TITLE
Design - [khochaynhalam] - Design the issues templates

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#29]
Dear @LieuTran287 ,

Please help me design the issues templates

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok thanks
