### ISSUE TITLE
Design - [khochaynhalam] - Design the board structure

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#30]
Dear @LieuTran287  ,

Please help me design the board structure

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.

Thanks,
Lieu
