### ISSUE TITLE
Design - [khochaynhalam] - Upgrade Recipe details page

### ISSUE THREAD

**Issue by LieuTran287** [khochaynhalam-dev/khochaynhalam-dev.github.io#32]
Dear @Vi1309  ,

Please help me upgrade Recipe details page based on style of Shop page.
**Estimate: 8h
Start date: 02/08/2020 - Due date: 05/08/2020**

Thanks,
Lieu

**Comment by Vi1309** [comment]
Dear @nhanntdl 

I will take this work.

Thanks
Vi

**Comment by Vi1309** [comment]
Dear @nhanntdl 

Tôi đã hoàn thành cái công việc này.
Làm ơn kiểm tra giúp tôi.

Thanks
Vi

**Comment by nhanntdl** [comment]
good
