### ISSUE TITLE
Fanpage - [khochaynhalam] - Write content to post on fanpage

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#33]
Dear @LieuTran287 

Please help me write some content to post on the fan page

Thanks,
TrungNhan

**Comment by Vi1309** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Log time today 16/04/2020:
 - Spent time: 0h
 - Done: N/A
 - Todo: complete this work
 - Problem: N/A

**Comment by LieuTran287** [comment]
Log time today 16/04/2020:
- Spent time: 1h
- Done: tìm ý tưởng cho bài viết trên fanpage
- Todo: tiếp tục hoàn thành task này
- Problem: N/A

**Comment by LieuTran287** [comment]
Log time today 17/04/2020:

Spent time: 0h
Done: N/A
Todo: tiếp tục hoàn thành task này
Problem: N/A

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

 - Spent time: 1h

 I had completed this work.
Please check my work in [link](https://docs.google.com/document/d/14LBOm3xrLXbWRnOETSpJGbqgGCA0Zfin/edit)

 Thanks,
 Lieu

**Comment by nhanntdl** [comment]
> Dear @nhanntdl ,
> 
> * Spent time: 1h
> 
> I had completed this work.
> Please check my work in [link](https://docs.google.com/document/d/14LBOm3xrLXbWRnOETSpJGbqgGCA0Zfin/edit)
> 
> Thanks,
> Lieu

Dear @LieuTran287 

I have checked your work
Your post is fine, but you have to post it on the fan page to count as the end of this task, so please help me post it on the fan page and log time again


Thanks
TrungNhan

**Comment by LieuTran287** [comment]
> > Dear @nhanntdl ,
> > 
> > * Spent time: 1h
> > 
> > I had completed this work.
> > Please check my work in [link](https://docs.google.com/document/d/14LBOm3xrLXbWRnOETSpJGbqgGCA0Zfin/edit)
> > Thanks,
> > Lieu
> 
> Dear @LieuTran287
> 
> I have checked your work
> Your post is fine, but you have to post it on the fan page to count as the end of this task, so please help me post it on the fan page and log time again, don't forget to push your post file to remote repository at [resources branch](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/resources)
> 
> Thanks
> TrungNhan

ok anh

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

- Spent time: 0.5h
- I have posted the article on the [fan page](https://www.facebook.com/khochaynhalam2020)
- Please check my work.

Thanks,
Lieu
