### ISSUE TITLE
Feature Request - [khochaynhalam] - Embed article on facebook into website  

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#36]
Dear @LieuTran287 ,

I think we should embed the article on Facebook on the website.

So, please help me research "how to embed the article on Facebook on the website" and create an example for it.

**Description:**
1. Learn how to embed the article on Facebook into the website
2. Restyle on it (you can work with @ Vi1309 to make the design more beautiful)
3. Commit your example code to `resource` branch
4. Actively create sub-tasks to perform this task

Thanks,
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will take this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Log time today 20/04/2020:

- Spent time: 0h
- Done: N/A
- Todo: continue work to complete this work.
- Problem: N/A

**Comment by LieuTran287** [comment]
Log time today 21/04/2020:

Spent time: 0.5h
Done: nghiên cứu css cho iframe nhúng bài viết trên fanpage vào trang web
Todo: tiếp tục nghiên cứu css cho iframe
Problem: N/A

**Comment by LieuTran287** [comment]
Log time today 22/04/2020:

- Spent time: 1.5h
- Done: nhúng được bài viết trên fanpage vào trang web
- Todo: hiển thị toàn bộ nội dung của bài viết trên fanpage trong trang web dùng iframe
- Problem: không biết phải làm thế nào khi nhúng bài viết của fanpage vào trang web mà không cần nút "xem thêm", sẽ hiển thị toàn bộ nội dung bài viết.
