### ISSUE TITLE
Q&A - [khochaynhalam] - Solutions for the task of embedding fanpage posts into webpages

### ISSUE THREAD

**Issue by LieuTran287** [khochaynhalam-dev/khochaynhalam-dev.github.io#38]
Dear @nhanntdl  @Huong111  @Vi1309  ,

-**Reference:**
Trong quá trình tìm hiểu cách nhúng bài viết trên fanpage vào trang web thì tôi đã nhúng được. Nhưng có một vấn đề là tôi không làm nó hiển thị hết tất cả nội dung của bài viết vào trang web được.

-**Question:**
Có ai có hướng giải quyết nào khác cho vấn đề này không?

-**My solution:**
Tôi sẽ nhúng bài viết trang fanpage vào trang web nhưng không cho hiển thị hết tất cả nội dung của bài viết. Khi người ta muốn xem tất cả nội dung thì sẽ vào fanpage để xem. Việc này nó cũng làm tăng lượt theo dỗi đến fanpage của mình.

Thanks,
Lieu

**Comment by nhanntdl** [comment]
Dear @LieuTran287 

I have asked our customer about your inquiries

The answer is:

1.  We have to create a `Posts` page to display the posts from the `Fanpage`
2.  We have to create a `Recipes` page to share the recipes for the followers

So, my solutions for this answer is:

1.  We have to create a `Posts` page to display the posts from the `Fanpage`
2.  We have to create a `Recipes` page to share the recipes for the followers
3.  We'll merge the `Services` page and the  `About Us` page into the single page called `About Us` page

So, with these solutions, we have 5 items in the menu:

1. Home
2. About Us
3. Recipes
4. Post
5. Contact Us

Please follow my solutions to do your [design task](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/issues/25)

Thanks
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will follow your solutions to do my design task which I'm working with Vi.
