### ISSUE TITLE
Design - [khochaynhalam] - Refactor to automic design

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#41]
Dear @chinhminh2025  ,

Please help me refactor my initial design to "atomic design" for `Recipes` screen
https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=728%3A167

/esstimate: 5h

Thanks,
TrungNhan

**Comment by chinhminh2025** [comment]
Dear @nhanntdl ,
I can spend 2h today for working on this task. I will mail to you after I done my work.
Thanks,
Chinh

**Comment by chinhminh2025** [comment]
Spent time: 2h
Done: 70%
Todo: 
- Add comment part to recipe page.
- Waitting for your comment about atomic design to make it better.
- Problem: I need more time to take the work up.

**Comment by chinhminh2025** [comment]
Dear @nhanntdl ,
I think I done my work. Please review it and let me know what I do wrong.
Thanks,
Chinh
