### ISSUE TITLE
Learn coding rule 

### ISSUE THREAD

**Issue by Huong111** [khochaynhalam-dev/khochaynhalam-dev.github.io#42]
Dear @all,

Please take time for me reviews [coding rule](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/blob/master/CONTRIBUTING.md) and please read it before I reviews.
Time: 19h30  May 26, 2020 
Estimate 3h.

Thanks,
Huong

**Comment by LieuTran287** [comment]
Dear @Huong111,

I will read your coding rule.
But tonight, I willn't take past in tranning with everyone.

Thanks,
Lieu

**Comment by Huong111** [comment]
Dear @LieuTran287 ,

Thanks for your interest.
If you don't understand them, you can ask me.

Thanks,
Huong

**Comment by chinhminh2025** [comment]
Dear @Huong111,
I can join the meeting but I don't have time to read your coding rule. I will do it after
Thanks,
Chinh

**Comment by chinhminh2025** [comment]
Dear @Huong111 ,
log time: 26/05/2020
spent time: 1 hour
done: 100%
Thanks,
Chinh
