### ISSUE TITLE
Create a notification for the customers

### ISSUE THREAD

**Issue by Huong111** [khochaynhalam-dev/khochaynhalam-dev.github.io#44]
Dear @LieuTran287  @Vi1309 @chinhminh2025 ,

This task informs the future work of you.
Please help me completed the following tasks: 
Design: @Vi1309  help me design the page. See details in the task [#45](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/issues/45)
Refactor: @LieuTran287 @chinhminh2025 help me check. See details in the task [#46](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/issues/46)

Thanks,
Huong

**Comment by chinhminh2025** [comment]
Dear @Huong111,
I read it. 
Thanks,
Chinh
