### ISSUE TITLE
Design - [khochaynhalam] -  Refactor to atomic design

### ISSUE THREAD

**Issue by Huong111** [khochaynhalam-dev/khochaynhalam-dev.github.io#46]
Dear @LieuTran287  @chinhminh2025  ,

Please read the [CONTRIBUTING](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/blob/master/CONTRIBUTING.md)  to get the job done: 
Help me check refactor to automic design [KCNL](https://khochaynhalam.com/?fbclid=IwAR3TPnlPKro5BQX5BfA1vow9DQ2ScxsC2TLTJTeQkftxXLOJOVZ_nAnZs1E) in [figma](https://www.figma.com/file/BMgH1CSWMBf6WeaG3Y4eXN/khochaynhalam.com?node-id=728%3A167).
#### Note: After design completion you proceed this work.

Thanks,
Huong

**Comment by chinhminh2025** [comment]
Dear @Huong111,
I read your task.
Thanks,
Chinh
