### ISSUE TITLE
CODING - [khochaynhalam] - Coding Header component

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#8]
Dear @LieuTran287 , @chinhminh2025  ,

Please help me implement for the `header` component based on the design:
The header for `home page`:
![image](https://user-images.githubusercontent.com/52454131/87808905-b9ffaa80-c884-11ea-8bc5-5dc09a4e8b38.png)
The header for `other page`:
![image](https://user-images.githubusercontent.com/52454131/87809514-b7ea1b80-c885-11ea-9942-45d7e8416fc6.png)

### /estimate: 5h

Thanks,
TrungNhan.

> CC
> 
> Dear @Huong111 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the header component, please help me review them's source code and please check the quality
> 
> Thanks,
> TrungNhan.

> CC
> 
> Dear @phamlinh221199 , @Vi1309 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the header component, please help me check it fits the design or not. Then inform them if it is incorrect.
> 
> Thanks,
> TrungNhan.

**Comment by LieuTran287** [comment]
Dear @phamlinh221199 , @Vi1309 , @Huong111

I had completed this work.
Spend time: 5h
Please check my work in [link](https://github.com/khochaynhalam-dev/khochaynhalam-dev.github.io/tree/ph1).
If it is incorrect, please inform me the wrong place.

Thanks,
Lieu
