### ISSUE TITLE
CODING - [khochaynhalam] - Coding footer component

### ISSUE THREAD

**Issue by nhanntdl** [khochaynhalam-dev/khochaynhalam-dev.github.io#9]
Dear @LieuTran287 , @chinhminh2025  ,

Please help me implement for the `footer` component based on the design:
![image](https://user-images.githubusercontent.com/52454131/87811513-fdf4ae80-c888-11ea-9e7b-f522bc58c7dd.png)

### /estimate: 5h

Thanks,
TrungNhan.

> CC
> 
> Dear @Huong111 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the footer component, please help me review them's source code and please check the quality
> 
> Thanks,
> TrungNhan.

> CC
> 
> Dear @phamlinh221199 , @Vi1309 ,
> 
> After @chinhminh2025 and @LieuTran287 finished coding for the footer component, please help me check it fits the design or not. Then inform them if it is incorrect.
> 
> Thanks,
> TrungNhan.

**Comment by chinhminh2025** [comment]
Dear @nhanntdl,
I have done this work
Spent time: 3h

Thanks,
Chinh
